title: my first github blog
author: https://github.com/teeliny
theme: minima
email: teeliny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog in github during my first task as a DecaDev 005 Squad(awaiting). I believe 
  in this most anticipated training. I am eager to learn from this moment.

# social links
twitter_username: https://twitter.com/teeliny # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/teeliny # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
